CREATE DATABASE Congtyvienthong;
USE Congtyvienthong;

CREATE TABLE KhachHang (
    ID_KhachHang INT AUTO_INCREMENT PRIMARY KEY,
    Ten VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL,
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE DichVu (
    ID_DichVu INT AUTO_INCREMENT PRIMARY KEY,
    TenDichVu VARCHAR(255) NOT NULL
);

CREATE TABLE GoiDichVu (
    ID_GoiDichVu INT AUTO_INCREMENT PRIMARY KEY,
    ID_DichVu INT,
    TenGoiDichVu VARCHAR(255) NOT NULL,
    TocDo VARCHAR(50),
    GiaTien DECIMAL(10, 2) NOT NULL,
    MoTa VARCHAR(255),
    FOREIGN KEY (ID_DichVu) REFERENCES DichVu(ID_DichVu)
);

CREATE TABLE NhanVien (
    ID_NhanVien INT AUTO_INCREMENT PRIMARY KEY,
    TenNhanVien VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL,
    Username VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE TTNhanVienBanHang (
    ID_TTNVBH INT AUTO_INCREMENT PRIMARY KEY,
    TenNhanVien VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL,
    ID_NhanVien INT,
    FOREIGN KEY (ID_NhanVien) REFERENCES NhanVien(ID_NhanVien)
);

CREATE TABLE ThongTinBanHang (
    ID_ThongTinBanHang INT AUTO_INCREMENT PRIMARY KEY,
    ID_KhachHang INT,
    ID_GoiDichVu INT,
    ID_TTNVBH INT,
    NgayDangKy DATE NOT NULL,
    SoLuong INT,
    FOREIGN KEY (ID_KhachHang) REFERENCES KhachHang(ID_KhachHang),
    FOREIGN KEY (ID_GoiDichVu) REFERENCES GoiDichVu(ID_GoiDichVu),
    FOREIGN KEY (ID_TTNVBH) REFERENCES TTNhanVienBanHang(ID_TTNVBH)
);

CREATE TABLE DoanhThu (
    ID_DoanhThu INT AUTO_INCREMENT PRIMARY KEY,
    ID_ThongTinBanHang INT,
    ThoiGian DATE NOT NULL,
    SoTien DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_ThongTinBanHang) REFERENCES ThongTinBanHang(ID_ThongTinBanHang)
);
